application_name: Google Drive Bulk Copy
client_secret_path: config/client_secret.json
ignored_file_extension_regexes:
    - jpg
    - metathumb
    - nfo
    - plexignore
    - png
    - r[0-9][0-9]
    - rar
    - sfv
    - txt
    - xml
